### ISSUE TITLE
Frontend: Optimize SQL query

### ISSUE THREAD

**Issue by dungphanxuan** [liufee/cms#10]
![image](https://user-images.githubusercontent.com/10725732/33301249-63368b28-d427-11e7-9dd2-68ea08b542cb.png)

Reference : [https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#lazy-loading-and-eager-loading-](https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#lazy-loading-and-eager-loading-)

**Comment by liufee** [comment]
Thanks for your advice. this has been optimized and will push at next commit.
![image](https://user-images.githubusercontent.com/7278053/33354339-55b7fc4a-d4ed-11e7-9eac-6ea58341d480.png)
