### ISSUE TITLE
后台删除存在问题

### ISSUE THREAD

**Issue by grandmasterLee** [liufee/cms#12]
例如文章，使用每篇文章后面的删除不起作用，而且页面一直处于删除状态，毫无反应；但是可以使用最上面的那个删除，选中文章后删除，是可以的，这是为什么？难道只有我存在这种问题吗?

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0
[]

**Comment by liufee** [comment]
你的php.ini配置有问题，报错了。set 'always_populate_raw_post_data' to '-1' in php.ini按照他的建议设置后试试
