### ISSUE TITLE
邮件发送失败

### ISSUE THREAD

**Issue by bigfool-cn** [liufee/cms#20]
'mailer' => [
            'class' => yii\swiftmailer\Mailer::className(),
            'viewPath' => '@common/mail',
            'useFileTransport' => false,//false发送邮件，true只是生成邮件在runtime文件夹下，不发邮件
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => ' smtp.163.com',  //每种邮箱的host配置不一样
                'username' => 'xxxxxx@163.com',
                'password' => 'xxxxx',
                'port' => '25',
                'encryption' => 'tls',
            ],
            'messageConfig' => [
                'charset' => 'UTF-8',
                'from' => ['xxxxxx@163.com' => 'Feehi CMS']
            ],
        ],

**Comment by liufee** [comment]
如果是阿里云/腾讯云机器，厂商会封杀25端口，更换其他加密端口即可，或者在本机调试可以看到邮件正常发送
