### ISSUE TITLE
日志模块应该加强

### ISSUE THREAD

**Issue by netyilei** [liufee/cms#21]
当array存储到JSON字段，就会提示字符串与array格式的问题
类似的问题很多  很多时候表单提交与修改的变量是array，日志就会出错了。

另外  个别文件的命名空间首字母用了大写   LINUX上会找不到文件。

总体说  程序做的很棒，大量简化了开发时间！   支持下！

**Comment by liufee** [comment]
感谢反馈，针对这个问题修复一下。麻烦提供具体的post参数以方便快速修复

**Comment by liufee** [comment]
已修复
