### ISSUE TITLE
访问后台报错 backend\components\Rbac::checkPermission() should not be called statically

### ISSUE THREAD

**Issue by wuyongguoke** [liufee/cms#3]
call_user_func() expects parameter 1 to be a valid callback, non-static method backend\components\Rbac::checkPermission() should not be called statically

components\Rbac line 38  public function checkPermission()  修改为  public static function checkPermission() 就不报错了  这样修改是否能不改变您的原意？

**Comment by liufee** [comment]
没有，已修复了。
