### ISSUE TITLE
cms对比分析

### ISSUE THREAD

**Issue by AlanLongYu** [liufee/cms#31]
首先我觉得作者的这种想法非常好。基于框架，以前我也尝试过多次从最初的ioize 到现在的laravel october 。一直在找寻一款比较优秀的cms.  fee嗨让我看到了希望。谢谢作者。
建议融入layerUI2 ，后台增加下载模型，广告位管理，等

**Comment by liufee** [comment]
感谢喜欢feehicms，
layerUI2不会接入的。作为后台，只要达到直观明了、开发速度快就可以了。
目前feehicms趋于稳定，不会再做一些皮肤类的接入了。除非是新的html组件
