### ISSUE TITLE
安装过程存在SQL注入漏洞(比较鸡肋)

### ISSUE THREAD

**Issue by qux-bbb** [liufee/cms#34]
在安装初期，选择数据库名没有做过滤，导致sql注入  
![image](https://user-images.githubusercontent.com/18598419/58072824-7e5f4700-7bd3-11e9-802a-0ba417cece50.png)
以其中一处举例  
install\controllers\SiteController.php  315行  
$dbname没有做任何限制  
```php
$db->createCommand("use $dbname")->execute();//判断用户名密码是否正确
$this->checkAccountPermission($db, $dbname);
```
使用burp拦截执行sleep比较，  
sleep 响应时间  
1  3087m  
5  15030m  
10  30009m  
如下图  
![image](https://user-images.githubusercontent.com/18598419/58073244-abf8c000-7bd4-11e9-8566-33f9b48e06ff.png)  
![image](https://user-images.githubusercontent.com/18598419/58073422-14e03800-7bd5-11e9-8382-a7c6fdfb6155.png)  
![image](https://user-images.githubusercontent.com/18598419/58073448-232e5400-7bd5-11e9-877e-273e26158fb4.png)  

**修复方式**  
限制变量$dbname，或修改SQL执行方式  
需要加以限制的有3行  
315  
425  
437

**Comment by liufee** [comment]
感谢反馈；
这个不是漏洞，安装永远是由管理员全安装。如果管理员都是不可靠的，那他直接删除数据库就行了。
程序只有第一次需要安装，上线之后的代码都是不可安装的。

**Comment by qux-bbb** [comment]
所以说比较鸡肋，感觉还是写成那种正式的形式比较好
