### ISSUE TITLE
Cross-site scripting vulnerability exists in Feehi cms

### ISSUE THREAD

**Issue by zKai1127** [liufee/cms#36]
Due to the lax filtering of tag parameters, JS code can be inserted to cause cross-site scripting attacks.If the tag parameter is assigned to "<script>alert(123)</script>".Submitting in get mode can cause cross-site script attack.
![TIM图片20190731121816](https://user-images.githubusercontent.com/52519142/62183690-b03c1900-b38d-11e9-9d1b-7d13e6a1b4c4.png)

The exp code is as follows：
http://127.0.0.1/index.php?r=search%2Ftag&tag=<script>alert(123)</script>

**Comment by willjzvip** [comment]
后台百度编辑器上传图片时，选择不了gif动画图片，jpg图片可以选择

**Comment by liufee** [comment]
fix
