### ISSUE TITLE
后台百度编辑bug

### ISSUE THREAD

**Issue by willjzvip** [liufee/cms#38]
后台用百度编辑器上传图片时，选择不了gif动画图片，jpg图片可以选择。

**Comment by willjzvip** [comment]
另外一个问题，当提交内容长度过长时（比如内容超过10000字），后台当日志记录会报错

**Comment by liufee** [comment]
这个不是bug，通过在ueditor返回的config中配置允许gif
内容过长，日志记录会报错，是因为message描述字段长度限制，修改数据库字段为longtext类型即可

**Comment by willjzvip** [comment]
config.json的配置没有修改过，允许上传的图片类型有png,gif,jpg,jpeg,bmp等
