### ISSUE TITLE
后台ueditor上传文件问题

### ISSUE THREAD

**Issue by willjzvip** [liufee/cms#39]
之前提交过一个bug，说是congif配置文件，后面才发现是后台的staic/js/plugins/ueditor/dialogs/image/image.js里面的文件问题。大概在365行左右有如下代码
`accept: {
                    title: 'Images',
                    extensions: acceptExtensions,
                    mimeTypes: 'image/jpg,image/jpeg,image/png'
                },`
只接受jpg、jpeg、png格式的图片上传，添加了image/gif之后就可以选择本地的gif图片上传了。

**Comment by liufee** [comment]
感谢反馈，为了方便大家，默认cms已经加上允许gif了，反倒是不允许gif的需要在这里单独去掉
