### ISSUE TITLE
File upload command execution

### ISSUE THREAD

**Issue by 19960903yzc** [liufee/cms#44]
In the background, you can upload the PHP file by changing the image suffix to PHP, resulting in command execution.

url：http://192.168.18.143/admin/index.php?r=admin-user%2Fupdate-self

![image](https://user-images.githubusercontent.com/50048558/68270629-dfeb7300-0098-11ea-9e5b-0e43c178498d.png)
![image](https://user-images.githubusercontent.com/50048558/68270658-feea0500-0098-11ea-86aa-599724f4fd5c.png)
![image](https://user-images.githubusercontent.com/50048558/68270662-05787c80-0099-11ea-8260-3ad9c6389d36.png)

**Comment by liufee** [comment]
thanks for the feedback.
it has been fix, see [commit](https://github.com/liufee/cms/commit/ecbfb0ca77874ead5b6e79b96a5e1f94e67475a9).
because yii2 FileValidator need custom assign value to attribute
