### ISSUE TITLE
Feehicms-2.0.8 can be attacked directly to getshell via the avatar uploads

### ISSUE THREAD

**Issue by tatsumaki002** [liufee/cms#46]
There is an arbitrary file upload vulnerability in the background avatar upload. 

The CMS only verified the suffix of the file in the front end by js, and we found that we could upload the PHP scripts directly after using Burp Suite for package capture modification.
![1](https://user-images.githubusercontent.com/50016287/70156592-21e6f380-16ef-11ea-8670-b4f167c53f7c.png)
The attacker can modify the box in the picture and upload the PHP script directly, It also returns the upload path(In the red box on the right of the figure above).

When the PHP file content is a Trojan,  attackers can get the shell directly.

Here I used  Behinder as a shell management tool, and getshell successfully.
![2](https://user-images.githubusercontent.com/50016287/70157118-f4e71080-16ef-11ea-9945-bc106298e259.png)
![3](https://user-images.githubusercontent.com/50016287/70157473-9cfcd980-16f0-11ea-96dd-f3f13bcfec96.png)
![4](https://user-images.githubusercontent.com/50016287/70157477-9e2e0680-16f0-11ea-97be-6c5e2bf9144f.png)

**Comment by liufee** [comment]
thanks for the feedback.
it has been fix, see [commit](https://github.com/liufee/cms/commit/ecbfb0ca77874ead5b6e79b96a5e1f94e67475a9).
because yii2 FileValidator need custom assign value to attribute
