### ISSUE TITLE
 Yii::$app->user->setReturnUrl(Url::current())后使用goback()跳转返回到了缓存的js路径

### ISSUE THREAD

**Issue by yaoyingkang** [liufee/cms#48]
Yii::$app->user->setReturnUrl(Url::current());之后在 return  $this->goBack(); 没有跳转到对应的控制器路径反而跳转到域名/assets/ebd9225d/jquery.js

**Comment by liufee** [comment]
你这个没有上下文，可以联系qq 1838889850阐明问题解决
