### ISSUE TITLE
后台头像管理模块存在任意文件上传getshell

### ISSUE THREAD

**Issue by whb5974** [liufee/cms#51]
1. The administrator will use the beforSave function in the /common/models/AdminUser.php file to modify the avatar.
This function will call Util's handleModelSingleFileUpload function
![图片](https://user-images.githubusercontent.com/9073269/77745128-b76b1200-7055-11ea-9f23-6b585fea1f6c.png)
2. We continue to use the handleModelSingleFileUpload function to find that the function directly calls the upload function without filtering the file name.
![图片](https://user-images.githubusercontent.com/9073269/77745176-ca7de200-7055-11ea-97e6-943ce16944cc.png)
3. We followed up the saveAs function and found that the temporary file was directly moved to an undetected file name.
![图片](https://user-images.githubusercontent.com/9073269/77745229-e1bccf80-7055-11ea-8b0a-5db8082b0500.png)
3. Vulnerability verification
![图片](https://user-images.githubusercontent.com/9073269/77745285-f731f980-7055-11ea-9eaf-07149308b4db.png)
![图片](https://user-images.githubusercontent.com/9073269/77745298-fb5e1700-7055-11ea-92f6-9187b75e62b3.png)
![图片](https://user-images.githubusercontent.com/9073269/77745372-192b7c00-7056-11ea-8f80-ebff20908c16.png)
![图片](https://user-images.githubusercontent.com/9073269/77745380-1c266c80-7056-11ea-9c1b-77a0e5758374.png)

**Comment by wfee** [comment]
![image](https://user-images.githubusercontent.com/10606229/78539380-0fa7ce00-7825-11ea-9fb3-64fae2d809d5.png)
已经修复了

**Comment by liufee** [comment]
![image](https://user-images.githubusercontent.com/7278053/78619828-fa788100-78b0-11ea-8ca1-b8848f5b6f5d.png)
