### ISSUE TITLE
cms后台设置->网站设置：统计代码处存在xss漏洞

### ISSUE THREAD

**Issue by niuzhi** [liufee/cms#56]
cms后台设置->网站设置：统计代码输入框未进行输入校验可以构造XSS
![image](https://user-images.githubusercontent.com/33443724/90307789-4779fd00-df0c-11ea-9f0e-353559619f88.png)
然后访问前台页面任何链接：
![image](https://user-images.githubusercontent.com/33443724/90307805-73957e00-df0c-11ea-9cc1-16a19176b374.png)

**Comment by wfee** [comment]
后台录入的数据是无条件信任的。因为这里就是需要插入js统计代码。

**Comment by liufee** [comment]
后台录入是无条件信任的。确实需要插入js代码才能实现功能。

**Comment by niuzhi** [comment]
> 后台录入是无条件信任的。确实需要插入js代码才能实现功能。

安全角度后台、前台都是需要进行严格校验。如果需要js，是否可以考虑白名单进行过滤
